import { app, BrowserWindow, ipcMain, screen, desktopCapturer } from 'electron';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { VoiceProcessor } from './voice-processor';
import { DeepgramSpeechService, DEEPGRAM_SETUP_INSTRUCTIONS, SpeechRecognitionResult } from './deepgram-service';

// Load environment variables from .env file
dotenv.config();
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create a minimal browser window for GrandPal (voice-only interface)
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 500,
    resizable: true,
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Don't open DevTools in production, only in development
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }

  // Set up IPC handlers for voice assistant functionality
  setupIpcHandlers();
  
  // Set up speech service event forwarding
  setupSpeechServiceEvents(mainWindow);
};

// Initialize speech service first, then voice processor with speech service reference
const speechService = new DeepgramSpeechService();
const voiceProcessor = new VoiceProcessor(speechService);

/**
 * Capture a screenshot of the primary display
 */
async function captureScreenshot(): Promise<string | null> {
  try {
    const primaryDisplay = screen.getPrimaryDisplay();
    const { width, height } = primaryDisplay.bounds;

    const sources = await desktopCapturer.getSources({
      types: ['screen'],
      thumbnailSize: { width, height }
    });

    if (sources.length > 0) {
      const primarySource = sources[0];
      // Convert to base64 data URL
      const dataURL = primarySource.thumbnail.toDataURL();
      console.log('Screenshot captured successfully');
      return dataURL;
    }
    return null;
  } catch (error) {
    console.error('Error capturing screenshot:', error);
    return null;
  }
}

// Set up IPC communication between main and renderer processes
function setupIpcHandlers(): void {
  // Handle voice commands
  ipcMain.handle('process-voice-command', async (event, command: string, screenshot?: string) => {
    console.log('Processing voice command:', command);
    try {
      const result = await voiceProcessor.processCommand(command, screenshot);
      return result;
    } catch (error) {
      console.error('Error processing voice command:', error);
      return { 
        response: 'Sorry, I had trouble understanding that. Could you try again?', 
        action: 'error',
        success: false 
      };
    }
  });

  // Handle screenshot capture
  ipcMain.handle('capture-screenshot', async (event) => {
    console.log('Capturing screenshot');
    try {
      const screenshot = await captureScreenshot();
      return { success: true, screenshot };
    } catch (error) {
      console.error('Error capturing screenshot:', error);
      return { success: false, error: error.message };
    }
  });

  // Handle speech recognition control
  ipcMain.handle('start-speech-recognition', async (event, language?: string) => {
    console.log('Starting speech recognition with language:', language);
    try {
      const success = await speechService.startListening(language || 'en');
      return { success };
    } catch (error) {
      console.error('Error starting speech recognition:', error);
      return { success: false, error: error.message };
    }
  });

  ipcMain.handle('stop-speech-recognition', async (event) => {
    console.log('Stopping speech recognition');
    try {
      speechService.stopListening();
      return { success: true };
    } catch (error) {
      console.error('Error stopping speech recognition:', error);
      return { success: false, error: error.message };
    }
  });

  // Add pause/resume handlers
  ipcMain.handle('pause-speech-recognition', async (event) => {
    console.log('Pausing speech recognition');
    try {
      speechService.pauseListening();
      return { success: true };
    } catch (error) {
      console.error('Error pausing speech recognition:', error);
      return { success: false, error: error.message };
    }
  });

  ipcMain.handle('resume-speech-recognition', async (event) => {
    console.log('Resuming speech recognition');
    try {
      speechService.resumeListening();
      return { success: true };
    } catch (error) {
      console.error('Error resuming speech recognition:', error);
      return { success: false, error: error.message };
    }
  });

  ipcMain.handle('is-speech-listening', async (event) => {
    return { listening: speechService.isCurrentlyListening() };
  });

  ipcMain.handle('is-speech-paused', async (event) => {
    return { paused: speechService.isCurrentlyPaused() };
  });

  // Handle filesystem operations
  ipcMain.handle('execute-filesystem-action', async (event, action: string, params: any) => {
    console.log('Executing filesystem action:', action, params);
    // This could be extended for more specific filesystem operations
    return { success: true, message: 'Action executed' };
  });

  // Handle text-to-speech
  ipcMain.handle('speak-text', async (event, text: string, language?: string) => {
    console.log('Speaking text:', text, 'Language:', language);
    try {
      const success = await voiceProcessor.speakText(text, language || 'en');
      return { success };
    } catch (error) {
      console.error('Error with TTS:', error);
      return { success: false };
    }
  });

  // Get Deepgram setup instructions
  ipcMain.handle('get-deepgram-instructions', async (event) => {
    return { instructions: DEEPGRAM_SETUP_INSTRUCTIONS };
  });

  // Get environment variable
  ipcMain.handle('get-env-var', async (event, name: string) => {
    return process.env[name] || '';
  });

  ipcMain.on('audio-chunk', (event, chunk) => {
    speechService.sendAudio(chunk);
  });

  ipcMain.on('stop-speaking', () => {
    voiceProcessor.stopSpeaking();
  });
}

// Set up speech service event forwarding to renderer
function setupSpeechServiceEvents(mainWindow: BrowserWindow): void {
  // Forward speech recognition events to renderer process
  speechService.on('transcript', (result: SpeechRecognitionResult) => {
    mainWindow.webContents.send('speech-transcript', result);
  });

  speechService.on('listening', (isListening: boolean) => {
    mainWindow.webContents.send('speech-listening-status', isListening);
  });

  speechService.on('paused', (isPaused: boolean) => {
    mainWindow.webContents.send('speech-paused-status', isPaused);
  });

  speechService.on('error', (error: any) => {
    mainWindow.webContents.send('speech-error', error);
  });

  // Forward fallback to browser speech recognition
  speechService.on('fallback-to-browser', (data: { language: string }) => {
    mainWindow.webContents.send('speech-fallback-to-browser', data);
  });
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
